server:
  port: 8071


encrypt:
  key: "APHJD&YG&*)#DJHA(*AGD(G(&&!@WG898123g9gsdyf078q73guaysgd0AWE"


spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/owinymarvin/microservice_test_springcloud_config.git"
          default-label: master
          timeout: 10
          clone-on-start: true
          force-pull: true
        # native:
            # search-locations: "classpath:/config"
            # search-locations: "file:///home//timothy//Desktop//CODE//SPRINGBOOT//Udemy//config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"


management:
  endpoints:
    web:
      exposure:
        include: "*"
