server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    # only works for local files ie /config or /file.
    # active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/owinymarvin/microservice_test_springcloud_config.git"
          default-label: master
          timeout: 10
          clone-on-start: true
          force-pull: true
        # native:
            # search-locations: "classpath:/config"
            # search-locations: "file:///home//timothy//Desktop//CODE//SPRINGBOOT//Udemy//config"
